findoutwho/hasbeen.in

config/travellers/eljojo.yml

hi :ice_cream: :icecream: :shaved_ice:

add eljojo

---

config/travellers/gueyeb.yml

add traveller gueyeb

---

config/travellers/onkelhotte.yml

Finally after planning it for all my previous vacations I've been in Vienna for a couple of days.
Just for sightseeing.
After arrival by car (about 500km / 5-6 hours from my hometown) I was quite sleepy but at least I checked out the location of my hotel a bit and went for Dinner in a nearby location: Austrian beer and [Kaiserschmarrn][1] - what a combination :laughing:.
On the second day I discovered the city a bit on my own by using the subway which was very handy since my hotel was just at the [Prater][2] :ferris_wheel: and it's station. Finally on the third and last day I decided to do the most tourist-like thing you can do to sightseeing: A hop-on-hop-off bus-tour.
I can only recommend visiting Vienna: It's a wonderful city with fantastic sights.
[1]: …

Add Vienna to onkelhotte.yml \o/

---

config/travellers/badboy.yml

Considering that I know live over here in Norway it's ok to say that I have been in Stavanger.
And just recently in London.

Add two more cities

---

config/travellers/renevolution.yml

as you are just sitting next to me .... here is the pull request

adding more cities

---

config/travellers/badboy.yml

Norway roundtrip (nearly) finished!

---

config/travellers/eljojo.yml

christmas yay! :santa: :gift: :snowman: :christmas_tree:

eljojo: add Copenhagen

---

README.md
app/helpers/location_helper.rb

Should be easier for most people, instead of tinkering with their /etc/hosts file. :)
(ping @dojobo)

Enable testing via xip.io domains.

---

README.md
app/app.rb
app/helpers/location_helper.rb
app/views/location/map.erb
app/views/location/overview.erb

re: #92, i struggled with the most elegant way to add this, e.g. by changing the index route in the controller, but couldn't figure out how to inject the proper username. a new route with a redirect didn't work either (since /:location was already in use) so here you have my solution :)
also, not sure if this is just me, but when i rackup with no args it's on port 9292, so i put this in the dev url template. however the readme still says 3000.

add home button to profiles & dev env tweaks

---

config/travellers/moonglum.yml

moonglum has a hometown, too

---

.travis.yml

This refs #139. Let's see if it works.

Wrestle Travis to build our stuff on something that's not legacy

---

lib/traveller.rb
spec/app/controllers/location_controller_spec.rb

location resolver ignores case

---

.travis.yml
README.md

…said no one ever in particular.
Still, Travis offers it out of the box – taking it for a spin.

WHO WANTS FASTER BUILDS?

---

config/travellers/eljojo.yml

Removed some ambiguity and added more places :)

eljojo: add more holidays!, i mean, places!

---

config/travellers/bitboxer.yml

I am in the nice Canada this week. First a couple of nice days in Montreal to see a 👶 and now visiting the capital to check it from my list.

Bodo in Ottawa 🇨🇦

---

config/travellers/ben.yml

since i am spending a couple of weeks every year in isreal, i've added some other places i stayed at least one night.
btw is this the rule for you also to have been in? stayed at least one night somewhere?

making hasbeen.in kosher again

---

config/travellers/eljojo.yml

eljojo: Add Montréal

---

config/travellers/pajowu.yaml

Fix pajowu.ymal

---

config/travellers/bitboxer.yml

I traveled a bit. I visited Copenhagen (which is beautiful) and took a
train to Stockholm (which I didn't like that much). Due to a train
problem I ended up in Malmö for 2 hours (which is also beautiful from
what I could see).
One little note for Stockholm: If you ever plan to visit a usergroup
there, don't show up in a nerd shirt. You will be the only one and feel
underdressed. Yes, even on a JS usergroup :wink:.

Bodo in Scandinavia

---

config/travellers/eljojo.yml

forgot about Steenwijk!

---

config/travellers/onkelhotte.yml

Had a nice trip to Paris 🇫🇷 last Thursday - Saturday 🎉
Although I've been sitting more in conference rooms than doing much sightseeing.

add paris to onkelhotte.yml

---

config/travellers/bascht.yml

* Bolzano (Been there as a kid!)
* Zürich (Visited a client)
* Sofia (euruko 2016!)
* Tenerife (on HOOOOOOOLIDAYS until last week)

Add a few (old and more current) places I have been to.

---

config/travellers/renevolution.yml

Some more cities added

---

config/travellers/badboy.yml

And this concludes my autumn trip. Time to fly home. ✈️

Concluding the autumn trip

---

config/travellers/eljojo.yml

add new cities in england

---

config/travellers/sebmel.yml

add SebMel
